parameters:
#    adim_app.example.class: Adim\AppBundle\Example

services:
#    adim_app.example:
#        class: %adim_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
